### ISSUE TITLE
Compatibility issue with PHP8

### ISSUE THREAD

**Issue by harpsicord86** [uwctri/AddValidationTypes#2] opened 2023-04-21 09:11 UTC
Hi @aanunez 

This is a really useful module you've made! It's allowed us to add our own validations that REDCap doesn't have built-in so thank you 👍 

Unfortunately, I may have found something which you may (or may not) be aware of. I've been testing this module within a REDCap PHP 8.1.17 and I can't seem to get any custom validation to work. Our live environment runs PHP 7.4.33 and works with no issues. Have I missed something or is this a genuine issue?

Thanks

**Comment by aanunez** [comment] 2023-04-21 13:37
Hi @harpsicord86 

I wasn't aware there was an issue with newer PHP versions, so thanks for letting me know. I've been trying to resolve some admin issue on my side stopping me from upgrading to 8.2 in prod/test so this EM was never tested against a newer version. To make things worse I'm also having docker issues on my laptop stopping me from easily testing on a newer php version. I'll be working on the later to see if I can push a fix soon. If you are able to share any php logs that might point to the issue please do. 

Thanks

**Comment by aanunez** [comment] 2023-05-18 21:30
Hey @harpsicord86 , I've finally got my dev environment back up and running. I do see an issue, it looks like my UI is dropping "+" characters from the Regex Repo in newer versions of redcap regardless of what version of PHP I am on. Could you elaborate further on the issue you are experiencing? Does the validation always fail/pass? Can you add new validation types?

**Comment by aanunez** [comment] 2023-05-18 22:08
Another update: I've resolved the issue I mentioned above, but I'll hold off on a release until I can confirm your issue. I'm not seeing any issue with any regex I've tested, so this might be unique to the pattern you are using (so please do share). I'm on PHP 8.1.19

**Comment by harpsicord86** [comment] 2023-05-19 08:27
Hi @aanunez 

Thanks for getting back to me. It does let me add new validation types but they don't seem to work on any of the instruments. Here is the pattern I'm using - NHS Number: \b\d{3} \d{3} \d{4}\b

**Comment by aanunez** [comment] 2023-05-19 17:18
This appears to be working as expected for me in Redcap 13.5.1 PHP 8.1.19
You can remove the "\b" at the beginning and end as we are forced to match the start/end of string using ^ and $, but that doesn't seem to be causing me any issue. 

What db and version are you using? I'm using MySQL 8.0.33 and similar in prod. Could you check what your "redcap_validation_types" table looks like in the db, specifically the row for NHS number? If you are using a different db or an older version of SQL then maybe something wasn't properly formatted when added (speculating).

Edit: Could you also check to see if there are any JS or PHP error being logged?

**Comment by aanunez** [comment] 2023-05-24 21:25
@harpsicord86 Pinging you again because I don't want to forget about pushing this update out.

**Comment by harpsicord86** [comment] 2023-05-31 08:08
Hi @aanunez so sorry for the late reply! I'm using REDCap 13.5.1 · PHP 8.1.18 (Linux/Unix OS) · MySQL 5.7.12
I'll try out your suggestions again to see if it is working on mine.

**Comment by aanunez** [comment] 2023-06-20 04:05
@harpsicord86 Welp, I forgot about this. Any update on your end?

**Comment by harpsicord86** [comment] 2023-06-20 09:31
Hi @aanunez,

No worries! I've been busy with work so I'm guilty of this too... I did manage to look at the logs and I couldn't see anything in there. Sadly, I can't look at the database because our REDCap instance is cloud-managed and I don't have direct access to the database.

**Comment by aanunez** [comment] 2024-04-19 21:37
Closing issue without clear resolution. EM is found to be working in my local dev on PHP8 and in a production environment using PHP8. The issue above is likely unrelated to the specific php version and some unique issue with environment/db settings.

**Closed as completed by aanunez** 2024-04-19 21:37 UTC
Labels: bug
